services:
  - type: web
    name: f1-race-analytics
    runtime: node
    plan: free

    buildCommand: |
      npm install
      npm run build

    startCommand: |
      npm start

    envVars:
      - key: NODE_ENV
        value: production
